### ISSUE TITLE
[warning] modshop GUI/client.luac is invalid

### ISSUE THREAD

**Issue by srcanseco** [404rq/GTW-RPG#75]
Server prompts "ERROR: modshop GUI/client.luac is invalid. Please re-compile at http://luac.mtasa.com/"

Whoever, all Transfender's GUI are working as expected, this is just a strange warning

**Comment by paa93** [comment]
Nothing to do about this except rewriting the entire mod shop system and it's GUI. Should be fixed for v3 tho.

**Comment by paa93** [comment]
Dropped support for v3.0 and replaced the mod shop completely in v4.0-beta
