### ISSUE TITLE
[outdated] Offline radio stations

### ISSUE THREAD

**Issue by srcanseco** [404rq/GTW-RPG#76]
A few radio stations are offline, I suggest to remove them; [reference](https://github.com/srcanseco/GTW-RPG/commit/4a5fb194e9483e71d2bc590c5cd893ed4f97297d)

**Comment by Anubhav652** [comment]
I will fix this in few hours.

**Comment by paa93** [comment]
Good :+1:

**Comment by Anubhav652** [comment]
Shouldn't this be closed/

**Comment by paa93** [comment]
It'll be closed once it's up and running on our own servers.

**Comment by paa93** [comment]
It's now up and running on our servers, closed
